# Registro de plugins que el microkernel cargara dinamicamente via Reflexion.
# clave=nombre.completo.de.la.Clase
plugin.1=co.edu.unicauca.microkernel.plugins.MultipleChoiceQuestionPlugin
plugin.2=co.edu.unicauca.microkernel.plugins.CaseQuestionPlugin
plugin.3=co.edu.unicauca.microkernel.plugins.MultimediaQuestionPlugin
